config/routes.rb
Sclassement::Application.routes.draw do
  resources :tags

  resources :salles

  resources :emplacements

  resources :positions

  resources :documents

  root :to => 'documents#index'

end

app/models/salle.rb
class Salle < ActiveRecord::Base
  attr_accessible :nom
end

app/controllers/salles_controller.rb
class SallesController < ApplicationController
  # GET /salles
  # GET /salles.json
  def index
    @salles = Salle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salles }
    end
  end

  # GET /salles/1
  # GET /salles/1.json
  def show
    @salle = Salle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @salle }
    end
  end

  # GET /salles/new
  # GET /salles/new.json
  def new
    @salle = Salle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @salle }
    end
  end

  # GET /salles/1/edit
  def edit
    @salle = Salle.find(params[:id])
  end

  # POST /salles
  # POST /salles.json
  def create
    @salle = Salle.new(params[:salle])

    respond_to do |format|
      if @salle.save
        format.html { redirect_to @salle, notice: 'Salle was successfully created.' }
        format.json { render json: @salle, status: :created, location: @salle }
      else
        format.html { render action: "new" }
        format.json { render json: @salle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salles/1
  # PUT /salles/1.json
  def update
    @salle = Salle.find(params[:id])

    respond_to do |format|
      if @salle.update_attributes(params[:salle])
        format.html { redirect_to @salle, notice: 'Salle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @salle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salles/1
  # DELETE /salles/1.json
  def destroy
    @salle = Salle.find(params[:id])
    @salle.destroy

    respond_to do |format|
      format.html { redirect_to salles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/salles_helper.rb
module SallesHelper
end

app/views/salles/_form.html.erb
<%= form_for(@salle) do |f| %>
  <% if @salle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salle.errors.count, "error") %> prohibited this salle from being saved:</h2>

      <ul>
      <% @salle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salles/edit.html.erb
<h1>Editing salle</h1>

<%= render 'form' %>

<%= link_to 'Show', @salle %> |
<%= link_to 'Back', salles_path %>

app/views/salles/index.html.erb
<h1>Listing salles</h1>

<table>
  <tr>
    <th>Nom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @salles.each do |salle| %>
  <tr>
    <td><%= salle.nom %></td>
    <td><%= link_to 'Show', salle %></td>
    <td><%= link_to 'Edit', edit_salle_path(salle) %></td>
    <td><%= link_to 'Destroy', salle, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Salle', new_salle_path %>

app/views/salles/new.html.erb
<h1>New salle</h1>

<%= render 'form' %>

<%= link_to 'Back', salles_path %>

app/views/salles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @salle.nom %>
</p>


<%= link_to 'Edit', edit_salle_path(@salle) %> |
<%= link_to 'Back', salles_path %>